#!/bin/bash
sudo dnf install curl -y
sudo dnf groupinstall "Xfce" -y
sudo dnf install xrdp xrdp-selinux -y
echo "exec startxfce4" > ~/.Xclients
chmod +x ~/.Xclients

sudo tee /etc/sysconfig/desktop << EOF PREFERRED=xfce4-session EOF

sudo firewall-cmd --add-port=3389/tcp --permanent
sudo firewall-cmd --reload

sudo systemctl enable xrdp --now
sudo setsebool-Pxrdp_can_connect_network 1
curl -fsSL https://tailscale.com/install.sh | sh
sudo tailscale up

echo "Optimizing DNF..."
echo -e "max_parallel_downloads=10\ndefaultyes=True" | sudo tee -a /etc/dnf/dnf.conf

# 3. Оновлення системи
echo "Updating system..."
sudo dnf upgrade -y

# 4. Встановлення групи віртуалізації та веб-панелі Cockpit
echo "Installing Virtualization stack and Cockpit..."
sudo dnf groupinstall -y "Virtualization Host"
sudo dnf install -y cockpit cockpit-machines cockpit-networkmanager cockpit-storaged

# 5. Активація сервісів
echo "Enabling services..."
sudo systemctl enable --now libvirtd
sudo systemctl enable --now cockpit.socket

# 6. Налаштування Firewall
echo "Configuring firewall..."
sudo firewall-cmd --permanent --add-service=cockpit
sudo firewall-cmd --permanent --add-service=libvirt
sudo firewall-cmd --reload
